name: Prueba

on:
  workflow_dispatch:

jobs:
  build-arm64-nswitch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/port'
    steps:
      - name: Install host dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git make cmake curl
      - name: Install devkitA64 docker image
        run: sudo docker pull devkitpro/devkita64:latest
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build pd.pal.arm64.nro
        run: sudo docker run --name pd --rm -v `pwd`:`pwd` -w `pwd` devkitpro/devkita64:latest bash ./tools/buildscripts/nswitch_docker.sh build_pal -DROMID=pal-final
      - name: Prepare artifact for packaging
        run: |
          mkdir -p bin/perfectdark_pal/data
          cp build_pal/pd.pal.arm64.nro bin/perfectdark_pal/
          touch bin/perfectdark_pal/data/put_your_rom_here.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pd-arm64-nswitch
          path: bin/
          retention-days: 0
